name: Review

on:
  workflow_call:

permissions:
  contents: read

jobs:
  # Review
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      # Harden Runner
      - name: Harden Runner # Audit all outbound calls
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # Dependency Review
      - name: Dependency Review
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 # v4.6.0
